### ISSUE TITLE
The configuration file environment

### ISSUE THREAD

**Issue by hwj0711** [IceClear/LDM-SRtuning#6]
Your project is very enlightening, but I have a doubt, this code runs in the configuration file environment.yaml you provided, the project does not run successfully, it will show an error like this:
_Traceback (most recent call last):
  File "D:\17DEM\LDM-SRtuning-main\main.py", line 6, in <module>
    import pytorch_lightning as pl
  File "D:\Anaconda\envs\diffusion\lib\site-packages\pytorch_lightning\__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "D:\Anaconda\envs\diffusion\lib\site-packages\pytorch_lightning\metrics\__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "D:\Anaconda\envs\diffusion\lib\site-packages\pytorch_lightning\metrics\classification\__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "D:\Anaconda\envs\diffusion\lib\site-packages\pytorch_lightning\metrics\classification\accuracy.py", line 16, in <module>
    from torchmetrics import Accuracy as _Accuracy
  File "D:\Anaconda\envs\diffusion\lib\site-packages\torchmetrics\__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "D:\Anaconda\envs\diffusion\lib\site-packages\torchmetrics\functional\__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "D:\Anaconda\envs\diffusion\lib\site-packages\torchmetrics\functional\audio\__init__.py", line 15, in <module>
    from torchmetrics.functional.audio.sdr import (
  File "D:\Anaconda\envs\diffusion\lib\site-packages\torchmetrics\functional\audio\sdr.py", line 27, in <module>
    solve = torch.linalg.solve
AttributeError: module 'torch.linalg' has no attribute 'solve'_

**Comment by hwj0711** [comment]
I solved it, but I can't call GPU training:
_GPU available: True, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs_
